snoplusweb/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from swap import urls as swap_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^swap/', include(swap_urls, namespace='swap')),
    url(r'^accounts/login/', 'django.contrib.auth.views.login', name='swap_login'),
    url(r'^accounts/logout/', 'django.contrib.auth.views.logout', name='swap_logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

swap/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
  url(r'^$', views.bookings, name='bookings'),
  url(r'^bookings/$', views.bookings_json, name='bookings_json'),
  url(r'^resources/$', views.ResourceList.as_view(), name='resource_list'),
]

swap/models.py
from django.db import models

from datetime import datetime, time, timedelta, timezone
from time import time as stime
import pytz

# Create your models here.

def now_utc():
  return datetime.now(timezone.utc)

def now_timestamp():
  return int(stime()) # seconds since epoch

class Zone(models.Model):
  name = models.CharField(max_length=40)

  def __str__(self):
    return "{0}".format(self.name)

class Resource(models.Model):
  # a resource to be swapped
  name = models.CharField(max_length=40) # short name
  description = models.TextField(blank=True) # more detailed description
  # also use to make name for static information page
  user_group = models.ForeignKey('auth.Group', related_name="user_resources") # can book themselves in
  admin_group = models.ForeignKey('auth.Group', related_name="admin_resources") # can mod bookings, book others
  # default booking information
  default_begin_time = models.TimeField(default=time(14,0)) # 2pm (in default_zone)
  default_end_time = models.TimeField(default=time(14,0)) # 12 noon (in default_zone)
  default_zone = models.ForeignKey('Zone', null=True, default=None)
  # maximum booking range
  advance_period = models.IntegerField(default=90) # days
  # history fields:  when this resource started/stopped taking bookings.
  # (a resource is active when a future booking date falls within range,
  # so to inactivate a resource we change close_time to current time)
  open_time = models.IntegerField(default=0) # UTC timestamp in seconds
  close_time = models.IntegerField(default=0) # UTC timestamp in seconds
  # bookkeeping
  modification_time = models.DateTimeField(auto_now=True) # store in UTC

  def __str__(self):
    return self.name

class Booking(models.Model):
  # a booking of a resource by a person
  user = models.ForeignKey('auth.User', related_name="user_bookings") # person for whom resource is booked
  booker = models.ForeignKey('auth.User', related_name="booker_bookings") # person booking the resource
  charge_group = models.ForeignKey('auth.Group', help_text='group to charge')
  resource = models.ForeignKey('Resource', related_name='booking')
  begin_time = models.IntegerField(default=0) # UTC timestamp in seconds
  end_time = models.IntegerField(default=0) # UTC timestamp in seconds
  request_time = models.DateTimeField(auto_now_add=True)
  modification_time = models.DateTimeField(auto_now=True)

  def __str__(self):
    t = datetime.fromtimestamp(self.begin_time, pytz.utc)
    return "{0} {1} ({2})".format(t, self.user, self.resource)

swap/views.py
from django.views.generic.list import ListView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User, Group
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.utils.timezone import utc, localtime, now, make_aware
import json
import logging
import time
import datetime
import pytz

from .models import Resource, Booking, Zone, now_timestamp

# Used for logging events
logger =  logging.getLogger(__name__)

# Create your views here.

class ResourceList(ListView):
  model = Resource

# bookings

@login_required
def bookings(request):
  messages = []
  if request.method == 'POST':
    # booking request or request approval
    # then redirect to bookings list
    logger.info('Bookings request')
    qs = request.POST
    s = request.body.decode('utf-8')
    logger.info('Request:  {0}'.format(s))
    data = json.loads(s)
    if data['mm'] == 'r':
      # request
      messages = request_resource(request.user, data)

    elif data['mm'] == 'x':
      # cancel booking
      logger.info('Delete ' + s)
      messages = delete_booking(request.user, data)

    elif data['mm'] == 'e':
      # edit booking
      logger.info('Edit ' + s)
      messages = change_booking(request.user, data)

    else:
      # unrecognized command
      messages = [ 'Unrecognized post response ' + s ]
      #return redirect('swap:bookings')

    # we'd also like to return updated list of bookings
    kwargs = {}
    for k,v in [ ('b0', 'begin_time__gte'), # minimum begin_time
                 ('b1', 'begin_time__lte'), # maximum begin_time
                 ('e0', 'end_time__gte'), # minimum end_time
                 ('e1', 'end_time__lte'), # maximum end_time
               ]:
      if k in data:
        n = data[k]
        kwargs[v] = n
    jb = find_bookings(kwargs)
    return JsonResponse({ 'b': jb, 'messages': messages })

  # respond to GET request
  context = { 'messages': messages }
  return render(request, 'swap/bookings_list.html', context)

# booking list in json form
@login_required
def bookings_json(request):
  # by default, go back 31 days, forward 92 days
  #now = datetime.datetime.now(datetime.timezone.utc)
  #past = (now + datetime.timedelta(-31))
  #future = (now + datetime.timedelta(92))
  logger.info('bookings_json')
  now = now_timestamp()
  sday = 24*60*60
  past = now - 31*sday
  future = now + 92*sday

  qd = request.GET
  kwargs = {}
  for k,v in [ ('u', 'user__pk'), # user
               ('b', 'booker__pk'), # booker
               ('c', 'charge_group__pk'), # group to charge
               ('r', 'resource__pk'), # resource id
             ]:
    n = qd.get(k)
    if n != None and n.isnumeric():
      kwargs[v] = int(n)
      logger.info('Bookings filter {0}: {1}'.format(v,n))
  for k,v in [ ('b0', 'begin_time__gte'), # minimum begin_time
               ('b1', 'begin_time__lte'), # maximum begin_time
               ('e0', 'end_time__gte'), # minimum end_time
               ('e1', 'end_time__lte'), # maximum end_time
             ]:
    n = qd.get(k)
    if n != None and n.isnumeric():
      kwargs[v] = int(n)
      logger.info('Bookings filter {0}: {1}'.format(v,n))

  jb = find_bookings(kwargs)
  logger.info('Bookings response = {0}'.format(jb))
  return JsonResponse({ 'b': jb })

#====================================================================

# fetch bookings according to QueryDict

def find_bookings(kwargs):
  # list bookings according to query
  logger.info('find_bookings')
  jb = []
  for b in Booking.objects.filter(**kwargs).order_by('begin_time'):
    #z = pytz.timezone(b.resource.default_zone.name)
    z = pytz.utc
    #tb = localtime(b.begin_time, z)
    #te = localtime(b.end_time, z)
    tr = localtime(b.request_time, z)
    tm = localtime(b.modification_time, z)
    jb.append({ 'bpk': b.pk,
                'u': b.user.pk,
                'b': b.booker.pk,
                'g': b.charge_group.pk,
                'r': b.resource.pk,
                'tb': b.begin_time,
                'te': b.end_time,
                'tr': date_array(tr),
                'tm': date_array(tm),
              })
  # above sends request and mod time arrays in UTC.
  return jb

def date_array(t):
  return [ t.year, t.month, t.day, t.hour, t.minute ]

# request/approve bookings

def request_resource(user, data):
  logger.info('request_resource')
  messages = []

  #ngs = user.groups.count()
  #if ngs >= 1:
  #  rg = user.groups.first()
  #else:
  #  rg = None
  #  messages.append('User {0} does not have a group'.format(user))

  gg = int(data['gg'])
  try:
    # is user a member of the group?
    rg = user.groups.get(pk=gg)
    #rg = Group.objects.get(pk=gg)
  except ObjectDoesNotExist:
    messages.append('Unknown group {0}'.format(gg))
    logger.error('Unknown group {0}'.format(gg))

  logger.info('Resources requested = {0}'.format(data['rr']))
  ri = [ int(e) for e in data['rr'] ]
  logger.info('  turned into numbers {0}'.format(ri))
  rr = []
  for e in ri:
    logger.info('resource pk = {0}'.format(e))
    try:
      rr.append(Resource.objects.get(pk=e))
    except ObjectDoesNotExist:
      messages.append('Illegal resource id {0} (internal error)'.format(e))
      # also need to check availability and conflicts

  upk = int(data['uu'])
  try:
    tenant = User.objects.get(pk=upk)
  except:
    messages.append('User {0} does not exist'.format(upk))

  logger.info('Resource request by booker {0} for user {1}'.format(user, tenant))

  if data['zz'] == "":
    messages.append('No time zone specified')
    return messages
  else:
    zone = pytz.timezone(data['zz'])
  td = data['bb']
  logger.info('  begin time {0}'.format(td))
  bdtu = int(td)
  #if td == "" or len(td) < 5:
  #  messages.append('Begin time invalid')
  #else:
  #  bdt = datetime.datetime(td[0], td[1], td[2], td[3], td[4]) # assume seconds = 0!
  #  bdtu = make_aware(bdt, zone)
  #  logger.info('  begin time aware {0}'.format(bdtu))
  td = data['ee']
  logger.info('  end time {0}'.format(td))
  edtu = int(td)
  #if td == "" or len(td) < 5:
  #  messages.append('End time invalid')
  #else:
  #  edt = datetime.datetime(td[0], td[1], td[2], td[3], td[4]) # assume seconds = 0!
  #  edtu = make_aware(edt, zone)
  #  logger.info('  end time aware {0}'.format(edtu))

  logger.info('Number of messages = {0}'.format(len(messages)))

  if len(messages) == 0:
    for e in rr:
      b = Booking(user=tenant, booker=user, charge_group=rg, resource=e,
                  begin_time=bdtu, end_time=edtu)
      b.save()
      logger.info('Booking created {0}'.format(b))

  return messages

# change a single booking

def change_booking(user, data):
  logger.info('change_booking')
  messages = []
  logger.info('Booking to modify = {0}'.format(data['pk']))
  bpk = int(data['pk'])
  logger.info('  to int = {0}'.format(bpk))

  gg = int(data['gg'])
  try:
    # is user a member of the group?
    rg = user.groups.get(pk=gg)
    #rg = Group.objects.get(pk=gg)
  except ObjectDoesNotExist:
    messages.append('Unknown group {0}'.format(gg))
    logger.error('Unknown group {0}'.format(gg))

  logger.info('Resource to update = {0}'.format(data['rr']))
  if len(data['rr']) != 1:
    messages.append('More than one resource to update')
    logger.error('More than one resource to update')
  else:
    ri = int(data['rr'][0])
    logger.info('Updated resource = {0}'.format(ri))
    try:
      rr = Resource.objects.get(pk=ri)
    except ObjectDoesNotExist:
      messages.append('Illegal resource id {0} (internal error)'.format(e))
      logger.error('Illegal resource id {0} (internal error)'.format(e))
      # also need to check availability and conflicts
    logger.info('Updated resource = {0}'.format(rr))

  upk = int(data['uu'])
  try:
    tenant = User.objects.get(pk=upk)
  except:
    messages.append('User {0} does not exist'.format(upk))
    logger.error('User {0} does not exist'.format(upk))

  logger.info('Resource request by booker {0} for user {1}'.format(user, tenant))

  if data['zz'] == "":
    messages.append('No time zone specified')
    logger.error('No time zone specified')
    return messages
  else:
    zone = pytz.timezone(data['zz'])
  td = data['bb']
  logger.info('  begin time {0}'.format(td))
  bdtu = int(td)
  td = data['ee']
  logger.info('  end time {0}'.format(td))
  edtu = int(td)

  logger.info('Number of messages = {0}'.format(len(messages)))

  if len(messages) == 0:
    Booking.objects.filter(pk=bpk).update(user=tenant, booker=user,
                                          charge_group=rg, resource=rr,
                                          begin_time=bdtu, end_time=edtu)
    logger.info('Booking updated')

  #Booking.objects.filter(pk=bpk).update()
  return messages

# delete bookings

def delete_booking(user, data):
  logger.info('delete_booking')
  messages = []
  logger.info('Bookings to delete = {0}'.format(data['pk']))
  bi = [ int(e) for e in data['pk'] ]
  if len(bi) > 0:
    b = Booking.objects.filter(pk__in=bi).delete()
  return messages

swap/templates/swap/bookings_report.html
{% extends "base.html" %}
{% load staticfiles %}
{% load tz %}
{% block title %}
Bookings report
{% endblock %}
{% block head %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href='{% static "js/jquery.dataTables.min.css" %}'>
<link rel="stylesheet" href='{% static "js/buttons.dataTables.min.css" %}'>
<link rel="stylesheet" href='{% static "js/jquery-ui-1.11.4/jquery-ui.min.css" %}'>
<link rel="stylesheet" href='{% static "js/jquery.multiselect.css" %}'>
<script src='{% static "js/jquery-1.12.0.min.js" %}'></script>
<script src='{% static "js/jquery.dataTables.min.js" %}'></script>
<script src='{% static "js/dataTables.buttons.min.js" %}'></script>
<script src='{% static "js/buttons.colVis.min.js" %}'></script>
<script src='{% static "js/buttons.print.min.js" %}'></script>
<script src='{% static "js/jquery-ui-1.11.4/jquery-ui.min.js" %}'></script>
<script src='{% static "js/jquery-cookie-1.4.1/jquery.cookie.js" %}'></script>
<script src='{% static "js/jquery.multiselect.min.js" %}'></script>
<script src='{% static "js/date.js" %}'></script>

<style>
input.dpicker { width: 6em }
input.tpicker { width: 6em }
p.centered { text-align: center; }
table.tcentered {
  margin-left: auto;
  margin-right: auto;
  border-collapse: collapse;
  border: 1px solid black;
}
td, th { padding: 5px; }
p#messages { color: red; }

.busy a {
  background-color: Green !important;
  background-image: none !important;
  color: White !important;
  font-weight: bold;
}
.conflict a {
  background-color: Red !important;
  background-image: none !important;
  color: White !important;
  font-weight: bold;
}
</style>
{% endblock %}
{% block content %}

<p>
<select id='select_resource' multiple='multiple'></select>
<select id='select_user' multiple='multiple'></select>
</p>

<p>
<table class='tcentered' border='1'>
<tr>
  <td><select id='res'><option value=""></option></select></td>
  <td><input id='startdate' class='dpicker' type='text'></td>
  <td><input id='stopdate' class='dpicker' type='text'></td>
  <td></td>
</tr>
<tr>
  <td><select id='tzs'><option value=""></option></select></td>
  <td><input id='starttime' class='tpicker' type='text'></td>
  <td><input id='stoptime' class='tpicker' type='text'></td>
  <td><button type='button' id='requestbutton'>Request</button></td>
</table>
</p>

<p id="messages"></p>

<p id='details'></p>

<p>
<table id='bookings' class='tcentered display' border='1'>
<thead>
  <tr>
    <th>Approved</th>
    <th>Begin date</th>
    <th>End date</th>
    <th>Resource</th>
    <th>Name</th>
  </tr>
</thead>
<tfoot>
  <tr>
    <th>Approved</th>
    <th>Begin date</th>
    <th>End date</th>
    <th>Resource</th>
    <th>Name</th>
  </tr>
</tfoot>
</table>
</p>

{% endblock %}
{% block scripts %}
<script>

// configuration information
var resources = [];
var users = [];
var groups = [];
var approvers = [];

// to add, busy_days[new Date()] = tooltip
var busy_days = {};
var conflict_days = {};

function update_days(data) {
  var bd = {};
  var rd = {};
  var cd = [];
  data.b.forEach(function(d,j) {
    var dt0 = new Date(d.b);
    dt0.clearTime();
    var dt1 = new Date(d.e);
    dt1.clearTime();
    var daybook = dt0.equals(dt1); // color anyway
    while (daybook || !dt0.equals(dt1)) {
      if (bd[dt0]) {
        if (bd[dt0].indexOf(users[d.u].n) < 0) bd[dt0].push(users[d.u].n);
      } else {
        bd[dt0] = [ users[d.u].n ];
      }
      if (rd[dt0]) {
        if (rd[dt0].indexOf(d.r) < 0) rd[dt0].push(d.r);
        else cd.push(dt0); // same resource on this day, potential conflict
      } else {
        rd[dt0] = [ d.r ];
      }
      if (daybook) break;
      else dt0.addDays(1);
    }
  });

  busy_days = {};
  conflict_days = {};
  $.each(bd, function(k,v) {
    busy_days[k] = v.join();
  });
  cd.forEach(function(d,j) {
    // check whether there's an overlap in time
  });
}

$.datepicker.setDefaults({
  //"dateFormat": "dd/mm/yy",
  "dateFormat": "dd M yy",
  "beforeShowDay": function(date) {
    var conflict = conflict_days[date];
    if (conflict) {
      return [ true, "conflict", conflict ];
    } else {
      var busy = busy_days[date];
      if (busy) {
        return [ true, "busy", busy ];
      } else {
        return [ true, '', '' ];
      }
    }
  }
});

// based on http://www.timlabonne.com/2013/07/parsing-a-time-string-with-javascript/
// understands 1pm, 1:00pm, 1:00p, 13:00.  Returns NaN if can't parse at all.
function parseTime(timeStr, dt) {
  if (!dt) {
    dt = new Date();
  }
 
  var time = timeStr.match(/(\d+)(?::(\d\d))?\s*(p?)/i);
  if (!time) {
    return NaN;
  }
  var hours = parseInt(time[1], 10);
  dt.setHours(hours);
  dt.setMinutes(parseInt(time[2], 10) || 0);
  dt.setSeconds(0, 0);
  return dt;
}

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}

var csrftoken = $.cookie('csrftoken');
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});
//"csrfmiddlewaretoken" is a key in your posted data,for example,
//when you need to ajax login,your posted data may like this:
// {'username':'username','password':'password',
//  'csrfmiddlewaretoken':'CSRF-TOKEN-V<U+200C><U+200B>ALUE'} – 

var old_default_begin = "";
var old_default_end = "";
var old_default_zone = "";

$(document).ready(function() {

  // get configuration information
  $.getJSON('{% static "json/config.json" %}', function(indata) {
    data = indata.data;
    var selres = $('#res');
    var selres2 = $('#select_resource');
    data.res.forEach(function(d,j) {
      selres.append('<option value="' + d.pk + '">' + d.name + '</option>');
      selres2.append('<option value="' + d.pk + '">' + d.name + '</option>');
      resources[d.pk] = d.name;
    });
    // set default value based on group (but may not exist)
    var seltzs = $('#tzs');
    data.tzs.forEach(function(d,j) {
      seltzs.append('<option value="' + d + '">' + d + '</option>');
    });
    //seltzs.val(data.tzs[0]);
    $('#starttime').prop('value', old_default_begin);
    $('#stoptime').prop('value', old_default_end);
    $('#tzs').val(old_default_zone);
    var seluser = $('#select_user');
    data.us.forEach(function(d,j) {
      users[d.pk] = { 'n': d.name, 'g': d.g };
      seluser.append('<option value="' + d.pk + '">' + d.name + '</option>');
    });
    data.gs.forEach(function(d,j) { groups[d.pk] = d.name });
    data.aps.forEach(function(d,j) { approvers.push({ 'u': d.u, 'r': d.r }) });

    $('#select_resource').multiselect({
      close: update_days_current,
      noneSelectedText: 'Select resources'
    });
    $('#select_user').multiselect({
      close: update_days_current,
      noneSelectedText: 'Select users'
    });
    $.getJSON('{% url "swap:bookings_json" %}', fill_bookings);
  });


  // datepickers
  $('#startdate').datepicker({
    defaultDate: '+1w',
    changeMonth: true,
    numberOfMonths: 3,
    onClose: function(selectedDate) {
      $('#stopdate').datepicker('option', 'minDate', selectedDate);
    }
  });
  $('#stopdate').datepicker({
    defaultDate: '+1w',
    changeMonth: true,
    numberOfMonths: 3,
    onClose: function(selectedDate) {
      $('#startdate').datepicker('option', 'maxDate', selectedDate);
    }
  });

  // buttons
  $('#requestbutton').click(function() {
    var bdt = $('#startdate').datepicker('getDate');
    parseTime($('#starttime').prop('value'), bdt);
    var edt = $('#stopdate').datepicker('getDate');
    parseTime($('#stoptime').prop('value'), edt);
    var reqs = { 'm': 'r',
                 'r': $('#res').val(), 
                 'b': [ bdt.getFullYear(), bdt.getMonth()+1, bdt.getDate(),
                        bdt.getHours(), bdt.getMinutes() ],
                 'e': [ edt.getFullYear(), edt.getMonth()+1, edt.getDate(),
                        edt.getHours(), edt.getMinutes() ],
                 'z': $('#tzs').val()
               };
    //console.log(JSON.stringify(reqs));
    //var qstring = window.location.href.slice(window.location.href.indexOf('?'));
    $.post('', JSON.stringify(reqs), function(data) {
      var msg = data.messages;
      var t = [];
      if (msg.length > 0) {
        t.push('<ul>');
        for (var i = 0; i < msg.length; ++i) t.push('<li>' + msg[i]);
        t.push('</ul>');
        $('#messages').html(t.join(''));
      } else {
        $('#messages').html('');
      }
    }, 'json');
    $.getJSON('{% url "swap:bookings_json" %}', fill_bookings);
  });
  //$('#tzs').select(function() {
  //});
  $('#res').change(function() {
    var r = $('#res').val();
    var rpk = 0;
    for (var i = 0; i < data.res.length; ++i) {
      if (r == data.res[i].pk) {
        rpk = i;
        break;
      }
    }
    var v = $('#starttime').prop('value');
    if (v == old_default_begin || v == "") {
      old_default_begin = data.res[rpk].dbt;
      $('#starttime').prop('value', old_default_begin);
    }
    v = $('#stoptime').prop('value');
    if (v == old_default_end || v == "") {
      old_default_end = data.res[rpk].det;
      $('#stoptime').prop('value', old_default_end);
    }
    v = $('#tzs').prop('value');
    if (v == old_default_zone || v == "") {
      old_default_zone = data.res[rpk].dz;
      $('#tzs').prop('value', old_default_zone);
    }
  });

});

var current_data = {};

function fill_bookings(data) {
  console.log('fill_bookings()');
  console.log(data);
  update_days(data);
  // need to do a deep copy of data to current_data;
  // or change update_days to select from persistent selectors
}

function update_days_current() {
  //update_days(current_data);
}

</script>
{% endblock %}